import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/flutter_flow/flutter_flow_widgets.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import 'product_information_model.dart';
export 'product_information_model.dart';

class ProductInformationWidget extends StatefulWidget {
  const ProductInformationWidget({super.key});

  @override
  State<ProductInformationWidget> createState() =>
      _ProductInformationWidgetState();
}

class _ProductInformationWidgetState extends State<ProductInformationWidget> {
  late ProductInformationModel _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => ProductInformationModel());
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      backgroundColor: Color(0xFFF5F5F5),
      appBar: AppBar(
        backgroundColor: Color(0xDFFEFEFE),
        iconTheme: IconThemeData(color: Color(0xFF282828)),
        automaticallyImplyLeading: true,
        title: Text(
          'Informações do Produto',
          style: FlutterFlowTheme.of(context).bodyMedium.override(
                fontFamily: 'Nunito',
                fontSize: 17,
                letterSpacing: 0.0,
              ),
        ),
        actions: [],
        centerTitle: true,
        elevation: 4,
      ),
      body: SafeArea(
        top: true,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              Padding(
                padding: EdgeInsets.all(17),
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Text(
                      'INFINITY OUTLET\n \nProdutos ORIGINAIS, LACRADOS, à PRONTA ENTREGA e com NOTA FISCAL!!\n \nFuja dos produtos FALSIFICADOS!! Aqui você compra com REVENDEDOR AUTORIZADO!!\n \nPrazo de Envio: só trabalhamos com produtos À PRONTA ENTREGA!\nTodos os produtos são despachados, no máximo, no dia SEGUINTE à compra.\nNossa entrega é feita pela transportadora do Mercado Livre! A entrega é bem mais rápida que a dos Correios!!\n \nPara saber o prazo de entrega, adicione o item desejado ao carrinho e digite seu CEP.\n \nDica Importante: adicione mais produtos do INFINITY OUTLET no carrinho para obter FRETE GRÁTIS nas compras acima de R\$ 99,00!! (Válido para a maioria das regiões. Consulte disponibilidade para seu endereço!)\n \nDescontos: já trabalhamos com o menor preço possível, mas, se deseja comprar maior quantidade de um mesmo item, podemos negociar. Consulte-nos no campo de perguntas!\n \nCONTÉM:\n \n01 Coffee Woman Seduction Colônia 100ml, O Boticário',
                      style: FlutterFlowTheme.of(context).bodyMedium.override(
                            fontFamily: 'Nunito',
                            letterSpacing: 0.0,
                          ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
