name: seloin
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  dropdown_button2: 2.3.9
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_credit_card: 4.0.1
  flutter_rating_bar: 4.0.1
  flutter_slidable: 3.0.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  lottie: 2.7.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  photo_view: 0.14.0
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  